### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by AkbarTheGreat** [AkbarTheGreat/cszb-scoreboard#11]
Add the ability to display a timer for games which require a timer.  Ideally as an element on the bottom of the screen, so other things may be displayed above it.

**Comment by hsq-cernansky** [comment]
If possible, I suggest white characters on a dark, translucent background, so you can still see what's under it. Was working on same for JANIS in 2018.

**Comment by AkbarTheGreat** [comment]
Solid advice, I took it.  This is now in the main branch and will be released with the next release.

**Comment by hsq-cernansky** [comment]
Excellent
