### ISSUE TITLE
Suggestion: Dropshadows when using white text

### ISSUE THREAD

**Issue by BrBill** [AkbarTheGreat/cszb-scoreboard#42]
I learned over the years that white text really pops with a dropshadow on brighter backgrounds and makes for much less eyestrain, and looks professional with little effort.

Looking at the demo images, the backgrounds are pretty bright, so I recommend using a darkish dropshadow when text is bright too. If background or text is darker, not really needed and maybe contraindicated. I use a function to determine whether the background brightness indicates shadow is needed (JANIS always shows text in white).

**Comment by AkbarTheGreat** [comment]
This is a really good idea -- it's easy to implement, could be a checkbox if anyone doesn't like it, and would just make things look a bit better in most cases.

The current setup uses white or black text based on some math as to which one would stand out better, but a contrasting drop-shadow on either one would be a nice touch.  I'll see if I can get this rolled in pretty quickly.

**Comment by BrBill** [comment]
Checkbox is a good idea. When I've added new features in the past, I made such a prefs checkbox for them, and then eventually phased out the checkbox if everybody liked the feature.
